version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: p2p_roulette_db
    environment:
      POSTGRES_DB: p2p_roulette
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: p2p_roulette_server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/p2p_roulette
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: p2p_roulette_client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules

volumes:
  postgres_data:
